name: Count Visitors

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes
  workflow_dispatch:

jobs:
  count:
    runs-on: ubuntu-latest
    steps:
      - name: Get current count
        id: get_count
        run: |
          echo "::set-output name=count::$(cat count.txt || echo 0)"

      - name: Increment count
        id: increment
        run: |
          new_count=$(( ${{ steps.get_count.outputs.count }} + 1 ))
          echo $new_count > count.txt
          echo "::set-output name=count::$new_count"

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add count.txt
          git commit -m "Update visitor count" || echo "No changes to commit"
          git push
